//! Integration tests against the .3dm fixtures generated by
//! `tests/fixtures/generate.py` (rhino3dm 8.x). The exact vertex/face counts
//! asserted here are printed by that script — regenerate the fixtures and
//! update the numbers together.

use rhino_mesh::{read_render_meshes, read_render_meshes_from, MeshPart, ReadError};
use std::path::PathBuf;

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

fn assert_part_invariants(part: &MeshPart) {
    assert_eq!(
        part.normals.len(),
        part.positions.len(),
        "normals length must match positions"
    );
    assert!(!part.indices.is_empty());
    assert_eq!(part.indices.len() % 3, 0, "triangle list");
    let vcount = part.positions.len() as u32;
    assert!(part.indices.iter().all(|&i| i < vcount), "indices in range");
    for n in &part.normals {
        let len = (n[0] * n[0] + n[1] * n[1] + n[2] * n[2]).sqrt();
        assert!((len - 1.0).abs() < 1e-3, "unit normal, got length {len}");
    }
}

#[test]
fn mesh_sphere_two_parts_with_color() {
    let model = read_render_meshes(&fixture("mesh_sphere.3dm")).expect("read");
    assert_eq!(model.parts.len(), 2);
    for part in &model.parts {
        assert_part_invariants(part);
    }

    // Part 0: UV sphere, radius 2 at origin — 42 vertices, 48 faces
    // (16 pole triangles + 32 body quads) -> 80 triangles.
    let sphere = &model.parts[0];
    assert_eq!(sphere.positions.len(), 42);
    assert_eq!(sphere.indices.len(), 80 * 3);
    assert_eq!(sphere.color, None);
    for p in &sphere.positions {
        let r = (p[0] * p[0] + p[1] * p[1] + p[2] * p[2]).sqrt();
        assert!((r - 2.0).abs() < 1e-4, "sphere vertex radius {r}");
    }
    // The sphere mesh was written with a normals array; on a sphere around
    // the origin every stored normal points away from the center.
    for (p, n) in sphere.positions.iter().zip(&sphere.normals) {
        let dot = p[0] * n[0] + p[1] * n[1] + p[2] * n[2];
        assert!(dot > 0.0, "stored normal should face outward");
    }

    // Part 1: 2x2 quad patch at z=5 — 9 vertices, 4 quads -> 8 triangles,
    // attribute color (210, 40, 20) with color source = from object.
    let patch = &model.parts[1];
    assert_eq!(patch.positions.len(), 9);
    assert_eq!(patch.indices.len(), 8 * 3);
    assert_eq!(patch.color, Some([210, 40, 20]));

    // Bounds: sphere dominates x/y at radius 2; the patch spans up to
    // (2, 2, 5).
    assert!((model.bounds_min[0] + 2.0).abs() < 1e-4);
    assert!((model.bounds_min[2] + 2.0).abs() < 1e-4);
    assert!((model.bounds_max[2] - 5.0).abs() < 1e-4);
}

#[test]
fn brep_render_meshes_one_part_per_face() {
    let model = read_render_meshes(&fixture("brep_with_render_mesh.3dm")).expect("read");
    // Box brep: 6 faces, each with a cached render mesh of 6 vertices and
    // 2 quads -> 4 triangles.
    assert_eq!(model.parts.len(), 6);
    for part in &model.parts {
        assert_part_invariants(part);
        assert_eq!(part.positions.len(), 6);
        assert_eq!(part.indices.len(), 4 * 3);
        assert_eq!(part.color, None);
    }
    // Face meshes are 2x1 patches at z = face index (0..=5), x in 0..=2,
    // y in 0..=1.
    assert!((model.bounds_min[2] - 0.0).abs() < 1e-4);
    assert!((model.bounds_max[2] - 5.0).abs() < 1e-4);
    assert!((model.bounds_max[0] - 2.0).abs() < 1e-4);
    assert!((model.bounds_max[1] - 1.0).abs() < 1e-4);
}

#[test]
fn extrusion_render_mesh_cache() {
    let model = read_render_meshes(&fixture("extrusion.3dm")).expect("read");
    // One extrusion whose render cache holds a unit UV sphere:
    // 20 vertices, 24 faces (12 pole triangles + 12 body quads) -> 36
    // triangles.
    assert_eq!(model.parts.len(), 1);
    let part = &model.parts[0];
    assert_part_invariants(part);
    assert_eq!(part.positions.len(), 20);
    assert_eq!(part.indices.len(), 36 * 3);
    for p in &part.positions {
        let r = (p[0] * p[0] + p[1] * p[1] + p[2] * p[2]).sqrt();
        assert!((r - 1.0).abs() < 1e-4, "cache sphere vertex radius {r}");
    }
}

#[test]
fn quads_are_triangulated_with_computed_normals() {
    let model = read_render_meshes(&fixture("quads.3dm")).expect("read");
    assert_eq!(model.parts.len(), 1);
    let part = &model.parts[0];
    assert_part_invariants(part);
    // 3x2 grid of quads: 12 vertices, 6 quads -> 12 triangles.
    assert_eq!(part.positions.len(), 12);
    assert_eq!(part.indices.len(), 12 * 3);
    // No normals array in the file: computed normals for a flat z=0 patch
    // must all be +z (counter-clockwise faces).
    for n in &part.normals {
        assert!((n[2] - 1.0).abs() < 1e-5, "computed normal {n:?}");
    }
}

#[test]
fn empty_file_reports_no_meshes() {
    assert!(matches!(
        read_render_meshes(&fixture("empty.3dm")),
        Err(ReadError::NoMeshes)
    ));
}

#[test]
fn garbage_bytes_are_not_a_3dm() {
    assert!(matches!(
        read_render_meshes_from(b"GIF89a definitely not a rhino file"),
        Err(ReadError::NotA3dm)
    ));
}

#[test]
fn truncated_file_errors_instead_of_panicking() {
    let bytes = std::fs::read(fixture("mesh_sphere.3dm")).expect("fixture");
    // Every prefix must produce an error or a valid (possibly partial)
    // model — never a panic.
    for len in [
        0usize,
        10,
        31,
        32,
        40,
        100,
        1000,
        bytes.len() / 2,
        bytes.len() - 1,
    ] {
        let _ = read_render_meshes_from(&bytes[..len]);
    }
    // A truncation inside the object table cannot yield a full model.
    assert!(read_render_meshes_from(&bytes[..bytes.len() / 2]).is_err());
}

#[test]
fn bit_flips_never_panic() {
    // Cheap fuzz: flip one byte at a stride through the brep fixture, which
    // exercises the deepest nesting (brep -> face mesh -> compressed
    // buffers).
    let bytes = std::fs::read(fixture("brep_with_render_mesh.3dm")).expect("fixture");
    for i in (0..bytes.len()).step_by(37) {
        let mut mutated = bytes.clone();
        mutated[i] ^= 0xA5;
        let _ = read_render_meshes_from(&mutated);
    }
}
