//! Slate keyboard, mouse, and navigation commands.
//!
//! **Rule:** every user-facing shortcut or input command must be registered in
//! [`SPECS`] and will appear automatically in Advanced → Commands & shortcuts.
//! See `COMMANDS.md` and `docs/keymap/` before adding or changing bindings.
//!
//! Commands are data ([`atlas_commands::CommandSpec`]): the reference UI, the
//! canvas palette, keyboard dispatch (`dispatch.rs`), and the F2 history all
//! read this one table, so they can never disagree (Constitution Art. VII).
//! Rows with `chord: None` are documentation for mouse gestures or keys that
//! are handled specially (Space/Enter repeat, Esc, Tab, arrows) or locally in
//! the board canvas.

use atlas_commands::{Availability, Chord, CommandId, CommandSpec, Key, Registry, Repeat};
use eframe::egui::Ui;

pub use atlas_shell::commands::{CommandEntry, TurboPanState};

const GLOBAL: Availability = Availability::GLOBAL;
const BOARD: Availability = Availability::BOARD_VIEW;
const BOARD_SEL: Availability =
    Availability(Availability::BOARD_VIEW.0 | Availability::NEEDS_SELECTION.0);

/// Shorthand spec constructor keeping the table readable (one row per
/// argument mirrors the `CommandSpec` fields; the arg count is the point).
#[allow(clippy::too_many_arguments)]
const fn spec(
    id: &'static str,
    category: &'static str,
    name: &'static str,
    binding: &'static str,
    chord: Option<Chord>,
    repeat: Repeat,
    when: Availability,
    aliases: &'static [&'static str],
) -> CommandSpec {
    CommandSpec {
        id: CommandId(id),
        name,
        category,
        binding,
        chord,
        repeat,
        when,
        aliases,
    }
}

const fn shift(key: Key) -> Chord {
    Chord {
        key,
        ctrl: false,
        shift: true,
        alt: false,
    }
}

const fn ctrl_shift(key: Key) -> Chord {
    Chord {
        key,
        ctrl: true,
        shift: true,
        alt: false,
    }
}

/// Canonical command table. Keep grouped by category (the reference UI groups
/// on category changes), documentation rows first within their historical
/// order, dispatchable additions after.
pub static SPECS: &[CommandSpec] = &[
    spec("app.updates.check", "Application", "Check for updates", "Advanced → Software updates", None, Repeat::Never, GLOBAL, &["version", "update"]),
    spec("app.updates.download", "Application", "Download update", "Update prompt → Download update", None, Repeat::Never, GLOBAL, &[]),
    spec("app.updates.install", "Application", "Update and restart", "Update prompt → Update and restart (save all workbooks first)", None, Repeat::Never, GLOBAL, &[]),
    spec("app.updates.later", "Application", "Dismiss update prompt", "Update prompt → Later", None, Repeat::Never, GLOBAL, &[]),
    spec("board.media.image", "Board", "Media: Image", "Media > Image: choose images, PDFs, or PowerPoint", None, Repeat::Repeatable, BOARD, &["image", "picture", "pdf", "powerpoint", "ppt", "print media"]),
    spec("board.media.model", "Board", "Media: 3D", "Media > 3D: choose a 3D model (Rhino, OBJ, STL, glTF, or a recognized file such as Blender, DWG, or SketchUp)", None, Repeat::Repeatable, BOARD, &["3d", "rhino", "model", "3dm", "obj", "stl", "gltf", "blend", "dwg", "skp"]),
    spec("board.media.video", "Board", "Media: Video", "Media > Video: place a video. Hover across it to scrub; click to play", None, Repeat::Repeatable, BOARD, &["video", "movie", "mp4", "scrub"]),
    spec("board.media.text", "Board", "Media: Text", "Media > Text: choose a Word document, spreadsheet, CSV, Excel workbook, or source file", None, Repeat::Repeatable, BOARD, &["text", "word", "docx", "excel", "xlsx", "csv", "spreadsheet", "code"]),
    spec("board.media.page", "Media", "Media: show page", "Selection strip Pages: browse the deck album over the selected PDF / PowerPoint", None, Repeat::Never, Availability::BOARD_VIEW, &["slide", "page", "poster page"]),
    spec("board.media.unbundle", "Board", "Media: unbundle pages", "Selection strip Pages: spread every page onto the board as a selected grid", None, Repeat::Never, BOARD_SEL, &["unbundle", "explode", "pages", "deck"]),
    spec("board.shape.edit", "Board", "Edit shape properties", "Selection strip: Fill / Stroke / Corners / Filters / Text / Bumper; RGB, opacity, stroke details, fillet/chamfer, photo-filter intensity, typeface, justification, font size, font color, bumper buffer and friction", None, Repeat::Never, BOARD, &["fill", "stroke", "fillet", "chamfer", "filter", "photo", "typeface", "bumper"]),
    spec("board.shape.text", "Board", "Edit shape text", "Double-click anywhere on a closed shape to open the text editor and a blinking caret. New text is center-justified", None, Repeat::Never, BOARD, &["shape text", "type in shape"]),
    spec("board.sheet.edit", "Board", "Edit spreadsheet cell", "Double-click a CSV or Excel card to open it. Click a cell, type, and press Enter. Save writes the file; clicking off asks when there are unsaved cells", None, Repeat::Never, BOARD, &["excel", "cell", "spreadsheet", "save"]),
    spec("board.sheet.scroll", "Board", "Scroll spreadsheet", "After a double-click into a CSV or Excel card, scroll the wheel to move through rows. Shift+scroll moves across columns. Drag a grid line to resize that row or column", None, Repeat::Never, BOARD, &["csv", "excel", "scroll", "rows"]),
    spec("board.sheet.column", "Board", "Add spreadsheet column", "With a CSV or Excel card open, hover and click + beside the header to add a column, then type its name", None, Repeat::Never, BOARD, &["excel column", "add column"]),
    spec("board.wire.edit", "Board", "Edit wire properties", "Wire selection palette: color, weight, Square / Bezier, Solid / Dashed, None / Arrows", None, Repeat::Never, BOARD, &["wire properties", "wire weight", "wire arrows", "wire dash"]),
    spec("board.shape.dimension", "Board", "Edit shape dimension", "Click an external dimension stringer; Enter applies around the center, Escape cancels", None, Repeat::Never, BOARD, &["dimension", "length", "width", "height"]),
    spec("board.color.desktop", "Board", "Sample desktop color", "Eyedropper in any color editor; click any desktop pixel, Escape cancels", None, Repeat::Never, BOARD, &["desktop color", "sample color"]),
    spec("board.tool.polyline", "Board", "Polyline tool", "Shapes: click vertices; Enter finishes; snap to the start to close", None, Repeat::Repeatable, BOARD, &["polyline", "polygon"]),
    spec("board.tool.arc", "Board", "Arc tool", "Shapes: pick three points for an arc", None, Repeat::Repeatable, BOARD, &["arc", "curve"]),
    spec("board.tool.bezier", "Board", "Bezier span tool", "Shapes: place anchors and drag tangent handles", None, Repeat::Repeatable, BOARD, &["bezier", "handles"]),
    // ----- Navigation -------------------------------------------------------
    spec(
        "nav.pan",
        "Navigation",
        "Pan (precise)",
        "Left-drag or right-drag on canvas background",
        None,
        Repeat::Never,
        GLOBAL,
        &[],
    ),
    spec(
        "nav.turbo_pan",
        "Navigation",
        "Turbo pan",
        "Ctrl + right-drag on canvas — pull away from the click point; speed scales with \
         distance; returns to zero at the origin; locked to horizontal or vertical",
        None,
        Repeat::Never,
        GLOBAL,
        &[],
    ),
    spec(
        "canvas.zoom",
        "Navigation",
        "Zoom",
        "Scroll wheel (pinch on trackpad)",
        None,
        Repeat::Never,
        GLOBAL,
        &[],
    ),
    spec(
        "canvas.pan_scroll",
        "Navigation",
        "Pan (scroll)",
        "Shift + scroll wheel",
        None,
        Repeat::Never,
        GLOBAL,
        &[],
    ),
    spec(
        "app.fullscreen",
        "Navigation",
        "Hide / show the bottom readout bar",
        "F11, or the lower-left chevron, or View → Hide readout bar",
        Some(Chord::bare(Key::F11)),
        Repeat::Repeatable,
        GLOBAL,
        &[],
    ),
    spec(
        "canvas.zoom_in",
        "Navigation",
        "Zoom in / out",
        "+ / −",
        None, // handled per-view next to fit
        Repeat::Never,
        GLOBAL,
        &[],
    ),
    spec(
        "canvas.minimap",
        "Navigation",
        "Minimap",
        "M",
        Some(Chord::bare(Key::M)),
        Repeat::Repeatable,
        GLOBAL,
        &["map", "overview"],
    ),
    spec(
        "canvas.tool.zoom",
        "Navigation",
        "Zoom tool",
        "Z — click = zoom in, Alt + click = out, drag = zoom window; \
         Esc or Z disarms (Board)",
        Some(Chord::bare(Key::Z)),
        Repeat::Never,
        Availability::BOARD_VIEW,
        &["magnify", "zoom window"],
    ),
    spec(
        "canvas.search",
        "Navigation",
        "Search canvas",
        "Ctrl + F — Enter / Shift+Enter cycle matches, Esc closes",
        Some(Chord::ctrl(Key::F)),
        Repeat::Repeatable,
        GLOBAL,
        &["find", "filter"],
    ),
    spec(
        "canvas.cycle_next",
        "Navigation",
        "Cycle objects (reading order)",
        "Tab / Shift+Tab",
        None, // handled specially (Shift variant + egui focus interplay)
        Repeat::Repeatable,
        GLOBAL,
        &[],
    ),
    spec(
        "canvas.pan_arrows",
        "Navigation",
        "Pan with arrows (nothing selected)",
        "Arrow keys with no selection (Shift = faster, Board view)",
        None, // arrows are handled specially (nudge vs pan)
        Repeat::Never,
        BOARD,
        &[],
    ),
    // ----- Files ------------------------------------------------------------
    spec(
        "files.open_host",
        "Files",
        "Open host document",
        "Double-click thumbnail",
        None,
        Repeat::Never,
        GLOBAL,
        &[],
    ),
    spec(
        "files.item_menu",
        "Files",
        "Item context menu (assign tags)",
        "Right-click thumbnail (without dragging)",
        None,
        Repeat::Never,
        GLOBAL,
        &[],
    ),
    spec(
        "app.add_files",
        "Files",
        "Add files to workbook",
        "Drop files onto the window, or Workbook → Add files…",
        None,
        Repeat::Repeatable,
        GLOBAL,
        &["import"],
    ),
    // ----- Selection ----------------------------------------------------------
    spec(
        "select.toggle",
        "Selection",
        "Toggle in selection",
        "Ctrl + click thumbnail",
        None,
        Repeat::Never,
        GLOBAL,
        &[],
    ),
    spec(
        "app.select_all",
        "Selection",
        "Select all visible",
        "Ctrl + A",
        Some(Chord::ctrl(Key::A)),
        Repeat::Never,
        GLOBAL,
        &[],
    ),
    spec(
        "app.cancel",
        "Selection",
        "Clear selection / dismiss",
        "Escape (pops one layer: draft → tool → selection → menus)",
        None, // Esc runs the cancel stack in dispatch.rs
        Repeat::Never,
        GLOBAL,
        &[],
    ),
    // ----- Workbook -----------------------------------------------------------
    spec(
        "app.home",
        "Workbook",
        "Home",
        "Icon portal → File → Home",
        None,
        Repeat::Never,
        GLOBAL,
        &[],
    ),
    spec(
        "app.new_tab",
        "Workbook",
        "New workbook tab",
        "Ctrl + N",
        Some(Chord::ctrl(Key::N)),
        Repeat::Never,
        GLOBAL,
        &["new"],
    ),
    spec(
        "app.open",
        "Workbook",
        "Open workbook",
        "Ctrl + O",
        Some(Chord::ctrl(Key::O)),
        Repeat::Never,
        GLOBAL,
        &[],
    ),
    spec(
        "app.save",
        "Workbook",
        "Save workbook",
        "Ctrl + S",
        Some(Chord::ctrl(Key::S)),
        Repeat::Never,
        GLOBAL,
        &[],
    ),
    spec(
        "app.save_as",
        "Workbook",
        "Save workbook as…",
        "Ctrl + Shift + S",
        Some(ctrl_shift(Key::S)),
        Repeat::Never,
        GLOBAL,
        &[],
    ),
    // ----- Board --------------------------------------------------------------
    spec(
        "board.tool.select",
        "Board",
        "Select tool",
        "V (Board view), or the combined Select/Pan bottom-dock button",
        Some(Chord::bare(Key::V)),
        Repeat::Repeatable,
        BOARD,
        &["arrow"],
    ),
    spec(
        "board.tool.pan",
        "Board",
        "Pan tool (hand)",
        "H, or middle-drag / Space + drag (Board view)",
        Some(Chord::bare(Key::H)),
        Repeat::Repeatable,
        BOARD,
        &["hand"],
    ),
    spec(
        "board.tool_swap",
        "Board",
        "Toggle Select ⇄ Pan",
        "Click the combined Select/Pan bottom-dock button while it is active",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.tool.frame",
        "Board",
        "Frame tool (slides)",
        "F — a small frame ghost follows the pointer; click or drag (Board view)",
        Some(Chord::bare(Key::F)),
        Repeat::Repeatable,
        BOARD,
        &["slide", "artboard"],
    ),
    spec(
        "board.tool.deck",
        "Board",
        "Deck",
        "Deck squircle on a selected frame — click frames, or draw a stroke through them",
        None,
        Repeat::Repeatable,
        BOARD,
        &["slides", "presentation order"],
    ),
    spec(
        "board.tools_row",
        "Board",
        "Shapes / Curve / Text tools",
        "R / O / L / T (Board view); click or hover a bottom-dock button to open its submenu",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.tool.rect",
        "Board",
        "Rectangle tool",
        "R — a small rectangle ghost follows the pointer; click or drag (Board view)",
        Some(Chord::bare(Key::R)),
        Repeat::Repeatable,
        BOARD,
        &["box", "square"],
    ),
    spec(
        "board.tool.ellipse",
        "Board",
        "Ellipse tool",
        "O — a small ellipse ghost follows the pointer; click or drag (Board view)",
        Some(Chord::bare(Key::O)),
        Repeat::Repeatable,
        BOARD,
        &["circle", "oval"],
    ),
    spec(
        "board.tool.line",
        "Board",
        "Line tool",
        "L (Board view)",
        Some(Chord::bare(Key::L)),
        Repeat::Repeatable,
        BOARD,
        &["segment"],
    ),
    spec(
        "board.portal.agent",
        "Board",
        "Agent portal",
        "Palette: agent portal; a small portal ghost follows the pointer; click or drag (Board view)",
        None,
        Repeat::Never,
        BOARD,
        &["agent portal", "cursor portal", "local agent"],
    ),
    spec(
        "board.portal.web",
        "Board",
        "Web portal",
        "Palette: web portal; click or drag places a Google start page; drop a page link or URL text to create/rebind a portal, paste a URL, or drop an .html file / index.html folder (Board view)",
        None,
        Repeat::Never,
        BOARD,
        &[
            "web portal",
            "embed",
            "web page",
            "iframe",
            "url",
            "dashboard",
            "html",
        ],
    ),
    spec(
        "board.portal.atlas",
        "Board",
        "File Atlas lens portal",
        "Palette: file atlas; click or drag places an unbound folder map; drop a folder to choose a lens (Board view)",
        None,
        Repeat::Never,
        BOARD,
        &["file atlas", "atlas lens", "folder lens", "folder portal"],
    ),
    spec(
        "board.portal.slate",
        "Board",
        "Slate board portal",
        "Palette: slate board; click or drag places an unbound frame; drop a .slate file on a board that already has content to open or insert it",
        None,
        Repeat::Never,
        BOARD,
        &["slate board", "nested board", "workbook portal"],
    ),
    spec(
        "portal.slate.source",
        "Board",
        "Slate board: choose workbook",
        "Portal menu or empty-state button; binds a local .slate file",
        None,
        Repeat::Never,
        BOARD,
        &["choose workbook", "bind workbook", "slate source"],
    ),
    spec(
        "portal.slate.refresh",
        "Board",
        "Slate board: refresh",
        "Reload the bound workbook from disk",
        None,
        Repeat::Never,
        BOARD,
        &["refresh workbook", "reload board"],
    ),
    spec(
        "portal.slate.open",
        "Board",
        "Slate board: open workbook",
        "Open the bound workbook as a tab",
        None,
        Repeat::Never,
        BOARD,
        &["open workbook", "open nested board"],
    ),
    spec(
        "portal.atlas.source",
        "Board",
        "File Atlas: choose folder",
        "Portal sidebar or empty-state button; binds a local folder",
        None,
        Repeat::Never,
        BOARD,
        &["choose folder", "bind folder", "atlas source"],
    ),
    spec(
        "portal.atlas.refresh",
        "Board",
        "File Atlas: refresh",
        "Portal sidebar; restarts the folder scan",
        None,
        Repeat::Repeatable,
        BOARD,
        &["atlas refresh"],
    ),
    spec(
        "portal.atlas.bake",
        "Board",
        "File Atlas: bake poster",
        "Portal sidebar; writes a poster of the current view as an authored image; the portal stays live",
        None,
        Repeat::Never,
        BOARD,
        &["atlas bake", "freeze folder"],
    ),
    spec(
        "portal.atlas.focus",
        "Board",
        "File Atlas: enter or leave contents",
        "Double-click the frame or this command; Esc leaves",
        None,
        Repeat::Never,
        BOARD,
        &["atlas focus", "enter folder"],
    ),
    spec(
        "portal.atlas.open",
        "Board",
        "File Atlas: open in File Atlas",
        "Opens the existing Slate-hosted File Atlas viewport on this folder",
        None,
        Repeat::Never,
        BOARD,
        &["open in file atlas", "atlas window"],
    ),
    spec(
        "portal.atlas.drag_out",
        "Board",
        "File Atlas: drag files to the board or another application",
        "In contents-focus, left-drag a file onto the Slate board to link and place it. Leave the window for a File Explorer-compatible shell drop (copy/link, never move). Esc cancels",
        None,
        Repeat::Never,
        BOARD,
        &["drag out", "drop files", "atlas drag"],
    ),
    spec(
        "portal.atlas.collapse",
        "Board",
        "File Atlas: expand or collapse folder",
        "In contents-focus, click a folder card to toggle it; the incremental grip opens one level, the full grip opens the subtree. Same grips as standalone File Atlas",
        None,
        Repeat::Never,
        BOARD,
        &["atlas expand", "atlas collapse"],
    ),
    spec(
        "portal.atlas.select",
        "Board",
        "File Atlas: select files",
        "In contents-focus, click a file to select it; Ctrl+click toggles it. Drag a box on empty canvas (or Shift-drag) to select multiple files. Drag a selected file to carry the selection",
        None,
        Repeat::Never,
        BOARD,
        &["atlas selection", "marquee"],
    ),
    spec(
        "portal.atlas.fit",
        "Board",
        "File Atlas: zoom to fit",
        "Fit the folder map to the portal window. Formatting squircle on a selected File Atlas portal",
        None,
        Repeat::Never,
        BOARD,
        &["atlas fit", "zoom to fit", "fit folder"],
    ),
    spec(
        "portal.web.source",
        "Board",
        "Web portal: choose page or file",
        "Portal sidebar or empty-state button; binds a URL, an .html file, or a folder with an entry file",
        None,
        Repeat::Never,
        BOARD,
        &["choose page", "bind url", "choose dashboard"],
    ),
    spec(
        "portal.web.allow_origin",
        "Board",
        "Web portal: allow this origin",
        "Portal sidebar; permits one remote origin for this workbook. Local trust only — never journaled or saved",
        None,
        Repeat::Never,
        BOARD,
        &["allow origin", "trust host", "permit site"],
    ),
    spec(
        "portal.web.home",
        "Board",
        "Web portal: home",
        "Portal sidebar; returns the live page to the authored locator without changing the workbook",
        None,
        Repeat::Never,
        BOARD,
        &["page home", "go home", "search home"],
    ),
    spec(
        "portal.web.reload",
        "Board",
        "Web portal: reload",
        "Portal sidebar; reloads the bound page in place",
        None,
        Repeat::Repeatable,
        BOARD,
        &["reload page", "refresh embed"],
    ),
    spec(
        "portal.web.back",
        "Board",
        "Web portal: back",
        "In-page history for the focused portal. Following links changes what the frame shows, never what the workbook says",
        None,
        Repeat::Repeatable,
        BOARD,
        &["page back", "browser back", "history back"],
    ),
    spec(
        "portal.web.forward",
        "Board",
        "Web portal: forward",
        "In-page history for the focused portal, forward",
        None,
        Repeat::Repeatable,
        BOARD,
        &["page forward", "browser forward", "history forward"],
    ),
    spec(
        "portal.web.recapture",
        "Board",
        "Web portal: recapture poster",
        "Portal sidebar; retakes the cached still the frame shows when it is not live",
        None,
        Repeat::Repeatable,
        BOARD,
        &["recapture poster", "retake screenshot"],
    ),
    spec(
        "portal.web.focus",
        "Board",
        "Web portal: take input focus",
        "Double-click a pooled portal, or Enter on the selection; Esc releases without stopping it",
        None,
        Repeat::Never,
        BOARD,
        &["enter page", "interact with page"],
    ),
    spec(
        "portal.web.open_external",
        "Board",
        "Web portal: open in system browser",
        "Ctrl+double-click the frame, or the Portal sidebar button",
        None,
        Repeat::Never,
        BOARD,
        &["open in browser", "open externally"],
    ),
    spec(
        "portal.web.package",
        "Board",
        "Web portal: package into workbook folder",
        "Portal sidebar; copies a local page and its folder beside the workbook and rewrites the locator (a fork that names its origin)",
        None,
        Repeat::Never,
        BOARD,
        &["package page", "copy dashboard in"],
    ),
    spec(
        "portal.web.bake",
        "Board",
        "Web portal: bake poster",
        "Portal sidebar; adds the captured poster plus a provenance note as authored nodes, leaving the portal in place",
        None,
        Repeat::Never,
        BOARD,
        &["bake page", "freeze page"],
    ),
    spec(
        "portal.web.copy_url",
        "Board",
        "Web portal: copy URL",
        "Right-click the portal or its identity tab; copies the displayed locator",
        None,
        Repeat::Never,
        BOARD,
        &["copy url", "copy page address"],
    ),
    spec(
        "portal.web.paste_url",
        "Board",
        "Web portal: paste URL",
        "Right-click the portal or its identity tab; rebinds that portal to the clipboard locator (journaled)",
        None,
        Repeat::Never,
        BOARD,
        &["paste url", "change page"],
    ),
    spec(
        "portal.maximize",
        "Board",
        "Portal: maximize",
        "Four-corner maximize square (upper-right, or the web tab's window-control slot), or right-click → Maximize. Fills the window at the screen aspect and covers Slate chrome. Esc restores",
        None,
        Repeat::Never,
        BOARD,
        &["maximize portal", "full screen portal"],
    ),
    spec(
        "portal.chrome.toggle",
        "Board",
        "Portal: hide or show tab",
        "Right-click Hide tab or use this command to fold the web identity tab; hover the top interior to restore",
        None,
        Repeat::Never,
        BOARD,
        &["hide portal tab", "show portal tab"],
    ),
    spec(
        "portal.agent.bind",
        "Board",
        "Agent portal: select folder",
        "Empty-state Select folder or inspector; binds a project folder (journaled source)",
        None,
        Repeat::Never,
        BOARD,
        &["select folder", "bind agent folder", "agent project"],
    ),
    spec(
        "portal.agent.send",
        "Board",
        "Agent portal: send prompt",
        "Enter in the agent composer sends; Shift+Enter inserts a new line",
        None,
        Repeat::Never,
        BOARD,
        &["send agent prompt", "cursor send"],
    ),
    spec(
        "portal.agent.provider",
        "Board",
        "Agent portal: choose provider",
        "Agent portal inspector; toggles the provider binding",
        None,
        Repeat::Never,
        BOARD,
        &["agent provider", "cursor provider"],
    ),
    spec("portal.agent.wire_output", "Board", "Image wire: toggle whole bundle", "Toggle between all images and a pinned current image on the selected wire", None, Repeat::Never, BOARD, &["all images", "pin current image", "image wire output"]),
    spec("portal.agent.unbundle", "Board", "Agent portal: unbundle images", "Split completed images into independent generator portals, in one undo step", None, Repeat::Never, BOARD, &["unbundle", "split image bundle"]),
    spec("portal.agent.stop", "Board", "Agent portal: stop response", "Interrupt this portal's Codex, Cursor, or ComfyUI run", None, Repeat::Never, BOARD, &["stop agent", "cancel generation"]),
    spec("portal.agent.train", "Board", "Agent: show chat train", "Present linked messages as top-aligned cards", None, Repeat::Never, BOARD, &["chat train"]),
    spec("portal.agent.pairs", "Board", "Agent: message pairs", "One user message and its reply on each card", None, Repeat::Never, BOARD, &["message pairs"]),
    spec("portal.agent.model", "Board", "Agent: choose model", "Click the model name to choose the next Codex or Ollama model, or a ComfyUI checkpoint (Auto picks one for the wired inputs)", None, Repeat::Never, BOARD, &["agent model", "checkpoint"]),
    spec("portal.agent.live", "Board", "Generator: live render", "Hover a ComfyUI generator and press Live. It re-renders when the wired model's camera, the prompt, or the checkpoint changes; double-click the card to fly the model from it", None, Repeat::Never, BOARD, &["live style", "style transfer", "live render"]),
    spec("portal.agent.keep", "Board", "Generator: keep live frame", "Press Keep on a live generator. The shown frame stays in the album and rendering continues", None, Repeat::Never, BOARD, &["keep frame", "save live frame"]),
    spec("portal.agent.rename", "Board", "Agent: rename conversation", "Click the conversation name in the header to rename the connected branch", None, Repeat::Never, BOARD, &["rename chat"]),
    spec("portal.agent.continue", "Board", "Agent: place continuation", "Click or drag the terminal output handle to place a message", None, Repeat::Never, BOARD, &["continue chat"]),
    spec("portal.agent.spawn", "Board", "Agent: text or image from this media", "Select a picture, video, 3D model, text or generated frame, open its Agent squircle, choose Text or Image, write the prompt and Submit; or click a generator's output port. A new frame appears downstream, wired to the matching input port, and runs", None, Repeat::Never, BOARD, &["image agent", "text agent", "describe image", "style transfer", "chatgpt image", "spawn node"]),
    spec("portal.agent.approval", "Board", "Agent: answer permission request", "Allow once or deny a provider tool request", None, Repeat::Never, BOARD, &["permission"]),
    spec("portal.agent.artifacts", "Board", "Agent: show artifacts", "Click a coding-agent reference or changed-document handle", None, Repeat::Never, BOARD, &["references", "changed files"]),
    spec("portal.agent.open_artifact", "Board", "Agent: open artifact portal", "Choose an artifact from its handle list", None, Repeat::Never, BOARD, &["open reference"]),
    spec("portal.agent.spawn_output", "Board", "Agent: spawn or retract an output", "Click a capsule in a chat card's output stack, or drag it onto the board to place it at the drop point", None, Repeat::Never, BOARD, &["deliverable", "changed file", "spawn artifact"]),
    spec("portal.agent.spawn_outputs", "Board", "Agent: spawn outputs as a group", "Click Spawn all (or Spawn N after Shift-clicking capsules) in a chat card's output stack. A second press retracts the group", None, Repeat::Never, BOARD, &["spawn all", "deliverables", "group outputs"]),
    spec("portal.agent.evolution", "Board", "Agent: show a file's evolution", "Click a capsule's vN badge in a chat card's output stack. A second click retracts the frame", None, Repeat::Never, BOARD, &["versions", "history", "evolution"]),
    spec("portal.agent.chat", "Board", "Agent: single chat window", "Collapse the conversation into one window per branch", None, Repeat::Never, BOARD, &["single chat"]),
    spec("portal.agent.bundle_chat", "Board", "Agent: bundle messages", "Collapse a consecutive selection without changing history", None, Repeat::Never, BOARD, &["bundle chat"]),
    spec("portal.agent.expand_chat", "Board", "Agent: expand messages", "Restore the original bundled message cards", None, Repeat::Never, BOARD, &["expand chat"]),
    spec("portal.agent.fork", "Board", "Agent: fork at checkpoint", "Compose a new branch at the selected message", None, Repeat::Never, BOARD, &["fork chat"]),
    spec("portal.agent.collapse", "Board", "Agent: collapse or expand card", "Click the chevron left of a chat card's ellipsis. Collapsed cards keep their first three lines, and the tail keeps its composer", None, Repeat::Never, BOARD, &["collapse chat", "expand chat card"]),
    spec("portal.agent.fit", "Board", "Agent: fit card to text", "Ellipsis menu → Fit to text, on a chat card you resized", None, Repeat::Never, BOARD, &["fit to text", "auto size chat"]),
    spec("portal.agent.schedule", "Board", "Agent: repeat a message", "Ellipsis menu → Schedule… opens a dialog: message, date and time (tonight, Oct 1, 4:55 am), and Once / Every hour / Every day / Every week. Runs through Windows Task Scheduler while Slate is closed; a clock in the card's top strip shows a pending schedule", None, Repeat::Never, BOARD, &["repeat", "schedule", "cron", "heartbeat"]),
    spec("portal.agent.full_access", "Board", "Agent: full access", "Ellipsis menu → Full access. This conversation runs commands and edits files without asking, from its next message. Stored for this user on this machine, never in the workbook", None, Repeat::Never, BOARD, &["full access", "allow all", "stop asking permission"]),
    spec("portal.agent.pocket", "Board", "Agent: show or pocket used context", "Click a chat card's lower context handle. Deleting context a card already sent pockets it into that card", None, Repeat::Never, BOARD, &["pocketed context", "restore context"]),
    spec("portal.agent.identity", "Board", "Agent: identity detail", "Name and top history anchors", None, Repeat::Never, BOARD, &[]),
    spec("portal.agent.summary", "Board", "Agent: summary detail", "Name and conversation excerpt", None, Repeat::Never, BOARD, &[]),
    spec("portal.agent.full", "Board", "Agent: full detail", "Full conversation and composer", None, Repeat::Never, BOARD, &[]),
    spec(
        "portal.agent.reveal",
        "Board",
        "Agent portal: reveal link folder",
        "Agent portal inspector; opens the session folder under the AI workspace",
        None,
        Repeat::Never,
        BOARD,
        &["agent link folder"],
    ),
    spec(
        "portal.agent.launch",
        "Board",
        "Agent portal: launch provider",
        "Opens the bound folder in Cursor (or the configured provider). Right-click or inspector",
        None,
        Repeat::Never,
        BOARD,
        &["launch cursor", "launch agent", "open in cursor"],
    ),
    spec(
        "portal.agent.focus",
        "Board",
        "Agent portal: take contents focus",
        "Double-click the frame, or Enter on the selection; Esc releases. Selection alone does not hand the wheel to Cover Flow",
        None,
        Repeat::Never,
        BOARD,
        &["enter agent portal", "interact with agent portal"],
    ),
    spec(
        "portal.agent.get_key",
        "Board",
        "Agent portal: get Cursor API key",
        "Opens the Cursor dashboard page where a user API key is minted, then paste it in the portal",
        None,
        Repeat::Never,
        BOARD,
        &["cursor api key", "get api key", "agent api key"],
    ),
    spec(
        "portal.agent.switch_chat",
        "Board",
        "Agent portal: switch agent",
        "After binding a project, pick an existing Cursor agent for that folder (or Switch agent later). Not a live IDE-thread attach.",
        None,
        Repeat::Never,
        BOARD,
        &["switch chat", "switch agent", "agent chat", "cursor chat"],
    ),
    spec(
        "stage.accept",
        "Board",
        "Accept staged agent proposal",
        "Agent portal inspector; commits the proposal as one attributed undo group",
        None,
        Repeat::Never,
        BOARD,
        &["accept proposal", "accept agent change"],
    ),
    spec(
        "stage.reject",
        "Board",
        "Reject staged agent proposal",
        "Agent portal inspector; writes a rejection result and leaves the board untouched",
        None,
        Repeat::Never,
        BOARD,
        &["reject proposal", "reject agent change"],
    ),
    spec(
        "board.tool.text",
        "Board",
        "Text tool",
        "T — a small text-box ghost follows the pointer; click to place (Board view); double-click text to edit",
        Some(Chord::bare(Key::T)),
        Repeat::Repeatable,
        BOARD,
        &["note", "label"],
    ),
    spec(
        "board.tool.pen",
        "Board",
        "Pen tool (freehand path)",
        "P (Board view)",
        Some(Chord::bare(Key::P)),
        Repeat::Repeatable,
        BOARD,
        &["draw", "freehand"],
    ),
    spec(
        "board.duplicate",
        "Board",
        "Duplicate",
        "Alt + drag selection, Alt + drag a scale handle (original stays), or Ctrl + D",
        Some(Chord::ctrl(Key::D)),
        Repeat::Repeatable,
        BOARD_SEL,
        &["copy in place"],
    ),
    spec(
        "board.resize_free",
        "Board",
        "Resize (free aspect / distort)",
        "Hover any edge or corner (no prior selection); Shift + drag corner \
         (corners scale proportionally by default); Shift + drag edge locks \
         aspect instead",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.resize_center",
        "Board",
        "Resize from center",
        "Ctrl + drag an edge or corner (Board view)",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.draw_square",
        "Board",
        "Draw square / circle",
        "Shift + drag with Frame, Rectangle, or Ellipse tool",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.draw_from_center",
        "Board",
        "Draw rectangle or ellipse from center",
        "Ctrl + drag with the Rectangle or Ellipse tool. Shift still locks a square or circle. The press point stays the center.",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.smart_guides",
        "Board",
        "Smart guides (align to objects)",
        "Preferences → Snaps. On by default; Alt suspends. \
         Only nearby objects in the same row or column participate.",
        None,
        Repeat::Repeatable,
        BOARD,
        &["align objects", "alignment guides"],
    ),
    spec(
        "board.snap_reach",
        "Board",
        "Smart-guide reach (cycle)",
        "Preferences → Snaps. Cycles Tight / Nearby / Wide.",
        None,
        Repeat::Repeatable,
        BOARD,
        &["snap reach", "snap neighborhood"],
    ),
    spec(
        "board.snap_reach.tight",
        "Board",
        "Smart-guide reach: Tight",
        "Only objects within ~160 px, same row or column",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.snap_reach.nearby",
        "Board",
        "Smart-guide reach: Nearby",
        "Default. Neighbors within ~360 px, same row or column",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.snap_reach.wide",
        "Board",
        "Smart-guide reach: Wide",
        "Anything in view that shares your row or column",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.rotate",
        "Board",
        "Rotate object",
        "Hover just outside a corner of a rotatable node (not a portal); drag \
         to rotate (snaps at 45°). With 2+ selected, rotates the group about \
         its center; portals in the group stay axis-aligned",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.group_resize",
        "Board",
        "Group resize (multi-selection)",
        "With 2+ selected, drag a group bounding-box edge or corner — scales \
         all members about the opposite corner/edge; corners scale \
         proportionally, Shift distorts, Ctrl scales from center. \
         Ctrl+Alt+Shift repositions members without changing their size",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.crop_enter",
        "Board",
        "Crop image (enter crop mode)",
        "Crop on the image selection strip, double-click an image, or \
         right-click → Crop image (images, PDF pages, video posters — \
         not 3D viewports or text snippets)",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.crop",
        "Board",
        "Crop selected image",
        "C with one or more croppable images selected (Board view)",
        Some(Chord::bare(Key::C)),
        Repeat::Repeatable,
        BOARD_SEL,
        &["mask"],
    ),
    spec(
        "board.crop_window",
        "Board",
        "Crop: move the window / pan the content",
        "In crop mode, drag a side blister to mask the image in place. \
         Every other selected croppable image takes the same crop as you drag",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.crop_finish",
        "Board",
        "Finish cropping",
        "Enter, Escape, or click outside the image (crop mode)",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.open_file",
        "Board",
        "Open image file",
        "Right-click object → Open file (double-click enters crop mode instead)",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.text_finish",
        "Board",
        "Finish text editing",
        "Escape, or click anywhere outside the text box",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.grid",
        "Board",
        "Board grid",
        "G or F7, or Preferences → Grid",
        Some(Chord::bare(Key::G)),
        Repeat::Repeatable,
        BOARD,
        &["dots"],
    ),
    spec(
        "board.snap_grid",
        "Board",
        "Snap to grid",
        "F9, or Preferences → Snaps → Snap to grid",
        Some(Chord::bare(Key::F9)),
        Repeat::Repeatable,
        BOARD,
        &["grid snap"],
    ),
    spec(
        "board.osnap",
        "Board",
        "Object snaps (master)",
        "Preferences → Snaps, or the command palette",
        None,
        Repeat::Repeatable,
        BOARD,
        &["osnap", "disable osnap"],
    ),
    spec(
        "board.dock.drop",
        "Board",
        "Drop toolbar to canvas",
        "Icon-strip two-dot column → Drop to canvas",
        None,
        Repeat::Never,
        BOARD,
        &["embed toolbar", "place toolbar"],
    ),
    spec(
        "board.dock.advanced",
        "Board",
        "Toolbar Advanced (on-strip tags)",
        "Retired from palette chrome; command surface keeps the id",
        None,
        Repeat::Never,
        BOARD,
        &["toolbar tags"],
    ),
    spec(
        "dock.bar.toggle",
        "Board",
        "Collapse / expand the primary toolbar",
        "Hover beside or below the icon bar (arrow) and click; blister on the readout redeploys",
        None,
        Repeat::Never,
        BOARD,
        &["collapse dock", "blister"],
    ),
    spec(
        "board.osnap.end",
        "Board",
        "Object snap: End",
        "Preferences → Snaps",
        None,
        Repeat::Repeatable,
        BOARD,
        &["end snap"],
    ),
    spec(
        "board.osnap.mid",
        "Board",
        "Object snap: Mid",
        "Preferences → Snaps",
        None,
        Repeat::Repeatable,
        BOARD,
        &["mid snap", "midpoint snap"],
    ),
    spec(
        "board.osnap.center",
        "Board",
        "Object snap: Center",
        "Preferences → Snaps",
        None,
        Repeat::Repeatable,
        BOARD,
        &["center snap", "cen"],
    ),
    spec(
        "board.osnap.near",
        "Board",
        "Object snap: Near",
        "Preferences → Snaps",
        None,
        Repeat::Repeatable,
        BOARD,
        &["near snap"],
    ),
    spec(
        "board.osnap.int",
        "Board",
        "Object snap: Intersection",
        "Preferences → Snaps",
        None,
        Repeat::Repeatable,
        BOARD,
        &["int snap", "intersection snap"],
    ),
    spec(
        "board.osnap.quad",
        "Board",
        "Object snap: Quadrant",
        "Preferences → Snaps",
        None,
        Repeat::Repeatable,
        BOARD,
        &["quad snap", "quadrant snap"],
    ),
    spec(
        "board.osnap.perp",
        "Board",
        "Object snap: Perpendicular",
        "Preferences → Snaps",
        None,
        Repeat::Repeatable,
        BOARD,
        &["perp snap", "perpendicular snap"],
    ),
    spec(
        "board.osnap.tan",
        "Board",
        "Object snap: Tangent",
        "Preferences → Snaps",
        None,
        Repeat::Repeatable,
        BOARD,
        &["tan snap", "tangent snap"],
    ),
    spec(
        "board.wire.routing",
        "Board",
        "Cycle wire routing",
        "Wire selection palette — cycle Bezier / Square; no selection sets creation default",
        None,
        Repeat::Repeatable,
        BOARD,
        &["wire style", "leader style"],
    ),
    spec(
        "board.wire.bezier",
        "Board",
        "Bezier wires",
        "Wire selection palette; no selection sets creation default",
        None,
        Repeat::Repeatable,
        BOARD,
        &["bezier wire", "curve wire"],
    ),
    spec(
        "board.wire.orthogonal",
        "Board",
        "Orthogonal wires",
        "Wire selection palette; no selection sets creation default",
        None,
        Repeat::Repeatable,
        BOARD,
        &["ortho wire", "elbow wire", "pcb wire"],
    ),
    spec(
        "board.ortho",
        "Board",
        "Ortho (45° constraint)",
        "F8 — the constraint applies to drags in a later wave; Shift inverts while held",
        Some(Chord::bare(Key::F8)),
        Repeat::Repeatable,
        BOARD,
        &["orthogonal", "axis lock"],
    ),
    spec(
        "board.align.left",
        "Board",
        "Align left",
        "Align widget on a 2+ selection — left-edge cluster, or command palette",
        None,
        Repeat::Never,
        BOARD_SEL,
        &["align left"],
    ),
    spec(
        "board.align.center_h",
        "Board",
        "Align horizontal centers",
        "Align widget on a 2+ selection — center of a horizontal cluster",
        None,
        Repeat::Never,
        BOARD_SEL,
        &["align center", "align middle horizontal"],
    ),
    spec(
        "board.align.right",
        "Board",
        "Align right",
        "Align widget on a 2+ selection — right-edge cluster",
        None,
        Repeat::Never,
        BOARD_SEL,
        &["align right"],
    ),
    spec(
        "board.align.top",
        "Board",
        "Align top",
        "Align widget on a 2+ selection — top of a vertical cluster",
        None,
        Repeat::Never,
        BOARD_SEL,
        &["align top"],
    ),
    spec(
        "board.align.middle_v",
        "Board",
        "Align vertical centers",
        "Align widget on a 2+ selection — center of a vertical cluster",
        None,
        Repeat::Never,
        BOARD_SEL,
        &["align middle", "align center vertical"],
    ),
    spec(
        "board.align.bottom",
        "Board",
        "Align bottom",
        "Align widget on a 2+ selection — bottom of a vertical cluster",
        None,
        Repeat::Never,
        BOARD_SEL,
        &["align bottom"],
    ),
    spec(
        "board.distribute.horizontal",
        "Board",
        "Distribute horizontally",
        "Align widget on a 3+ selection — fourth icon on a horizontal edge",
        None,
        Repeat::Never,
        BOARD_SEL,
        &["distribute horizontal", "space evenly horizontal"],
    ),
    spec(
        "board.distribute.vertical",
        "Board",
        "Distribute vertically",
        "Align widget on a 3+ selection — fourth icon on a vertical edge",
        None,
        Repeat::Never,
        BOARD_SEL,
        &["distribute vertical", "space evenly vertical"],
    ),
    spec(
        "board.delete",
        "Board",
        "Delete objects",
        "Delete or Backspace",
        Some(Chord::bare(Key::Delete)),
        Repeat::Never,
        BOARD_SEL,
        &["remove"],
    ),
    spec(
        "board.nudge",
        "Board",
        "Nudge objects",
        "Arrow keys (Shift = ×10)",
        None, // arrows handled specially (nudge vs pan)
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.marquee",
        "Board",
        "Marquee select",
        "Left-drag on empty board. Left to right selects only what is fully inside; right to left selects anything touched",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.pan_gestures",
        "Board",
        "Pan board",
        "H (hand tool), middle-drag, right-drag, or Space + left-drag",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.fit",
        "Board",
        "Fit board content",
        "Home (Board view)",
        Some(Chord::bare(Key::Home)),
        Repeat::Never,
        BOARD,
        &["fit board"],
    ),
    spec(
        "board.menu",
        "Board",
        "Object menu (z-order, tags, delete)",
        "Right-click object",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "app.undo",
        "Board",
        "Undo board edit",
        "Ctrl + Z",
        Some(Chord::ctrl(Key::Z)),
        Repeat::Never,
        GLOBAL,
        &[],
    ),
    spec(
        "app.redo",
        "Board",
        "Redo board edit",
        "Ctrl + Y (or Ctrl + Shift + Z)",
        Some(Chord::ctrl(Key::Y)),
        Repeat::Never,
        GLOBAL,
        &[],
    ),
    spec(
        "board.model_lock",
        "Board",
        "Unlock / lock 3D viewport",
        "Double-click a locked 3D model (or hover → click the padlock); \
         live viewports auto-lock after 30 s idle (the frozen view becomes \
         the slide image). Blender, DWG, SketchUp, and FBX use the same card \
         and say when no preview exists. An Enscape standalone opens inside \
         the card on double-click. A computer that cannot run it — not \
         Windows, a rotated card, or a file built for a different Windows \
         system — says so on the card. Slate never starts it on load",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.model_display",
        "Board",
        "3D display mode",
        "Viewport tools → Display: Shaded, Arctic (white clay), Material mask, or Z-buffer. The frozen poster uses the mode that was showing. The image generator still receives a shaded view and a depth pass",
        None,
        Repeat::Never,
        BOARD,
        &["arctic", "clay", "material id", "z-buffer", "depth"],
    ),
    spec(
        "board.model_orbit",
        "Board",
        "Orbit 3D model",
        "Drag inside an unlocked viewport (Rhino-style Z-up orbit)",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.model_pan",
        "Board",
        "Pan 3D model",
        "Shift + drag inside an unlocked viewport",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.model_zoom",
        "Board",
        "Zoom 3D model",
        "Scroll inside an unlocked viewport",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.path_finish",
        "Board",
        "Finish path",
        "Enter or double-click (Polyline / Bezier tools)",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.path_cancel",
        "Board",
        "Cancel path",
        "Escape while drawing a path",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.to_front",
        "Board",
        "Bring to front",
        "PageUp (Board view)",
        Some(Chord::bare(Key::PageUp)),
        Repeat::Repeatable,
        BOARD_SEL,
        &["front", "raise"],
    ),
    spec(
        "board.to_back",
        "Board",
        "Send to back",
        "PageDown or Ctrl + B (Board view)",
        Some(Chord::bare(Key::PageDown)),
        Repeat::Repeatable,
        BOARD_SEL,
        &["back", "lower"],
    ),
    spec(
        "board.copy",
        "Board",
        "Copy objects",
        "Ctrl + C (Board view; connectors between copied nodes come along)",
        Some(Chord::ctrl(Key::C)),
        Repeat::Repeatable,
        BOARD_SEL,
        &[],
    ),
    spec(
        "board.cut",
        "Board",
        "Cut objects",
        "Ctrl + X (Board view)",
        Some(Chord::ctrl(Key::X)),
        Repeat::Repeatable,
        BOARD_SEL,
        &[],
    ),
    spec(
        "board.paste",
        "Board",
        "Paste objects",
        "Ctrl + V — at the pointer when over the canvas, else at the view center; \
         repeated pastes step +24, +24. A copied image or files on the clipboard \
         land on the board.",
        Some(Chord::ctrl(Key::V)),
        Repeat::Repeatable,
        BOARD,
        &[],
    ),
    spec(
        "board.paste_in_place",
        "Board",
        "Paste in place",
        "Ctrl + Shift + V — paste at the source coordinates",
        Some(ctrl_shift(Key::V)),
        Repeat::Repeatable,
        BOARD,
        &[],
    ),
    spec(
        "board.image.adjust",
        "Board",
        "Image adjustments (popover)",
        "Ctrl + U with image(s) selected (Board view)",
        Some(Chord::ctrl(Key::U)),
        Repeat::Repeatable,
        BOARD_SEL,
        &["hue", "saturation", "brightness", "filters"],
    ),
    spec(
        "board.image.invert",
        "Board",
        "Invert image colors",
        "Ctrl + I with image(s) selected (Board view)",
        Some(Chord::ctrl(Key::I)),
        Repeat::Repeatable,
        BOARD_SEL,
        &["negative"],
    ),
    spec(
        "board.palette",
        "Board",
        "Canvas palette",
        "Double-click empty board — type to search commands, Enter places/executes",
        None, // opened from the double-click site in board.rs
        Repeat::Never,
        BOARD,
        &["command palette"],
    ),
    // ----- board: ink tools + color state (wave 2b) -------------------------
    spec(
        "board.tool.brush",
        "Board",
        "Brush tool (expressive ink)",
        "B — freehand stroke in the foreground color. [ ] size, Shift+[ ] \
         softness, Shift+click steps opacity, Shift+right-drag scrubs opacity, \
         Alt+right-drag scrubs size and softness from the press point, \
         Ctrl+right-drag opens the color wheel. Ctrl and Alt beat Shift.",
        Some(Chord::bare(Key::B)),
        Repeat::Repeatable,
        BOARD,
        &["ink", "paint"],
    ),
    spec(
        "board.brush.stroke",
        "Board",
        "Brush stroke",
        "Drag with the Brush tool",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.tool.eraser",
        "Board",
        "Eraser tool",
        "E — drag or click over painted brush strokes to erase just that ink \
         (soft, partial, and Shift-straight like the Brush); vector strokes \
         the eraser crosses are removed whole. Images, text, frames, and \
         wires are never erased. Esc cancels",
        Some(Chord::bare(Key::E)),
        Repeat::Repeatable,
        BOARD,
        &["erase", "remove strokes"],
    ),
    spec(
        "board.eraser.stroke",
        "Board",
        "Eraser stroke",
        "Drag with the Eraser tool",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.tool.eyedropper",
        "Board",
        "Eyedropper",
        "I — click samples the node color under the cursor into the \
         foreground; Alt+click samples into the background",
        Some(Chord::bare(Key::I)),
        Repeat::Repeatable,
        BOARD,
        &["sample", "color picker"],
    ),
    spec(
        "board.tool.sticky",
        "Board",
        "Sticky note",
        "N — a small sticky ghost follows the pointer; click places one note, \
         returns to Select, and opens a centered black caret. The fill strip \
         stays hidden while typing — Tab/Shift+Tab while editing spawns an \
         adjacent sticky",
        Some(Chord::bare(Key::N)),
        Repeat::Repeatable,
        BOARD,
        &["sticky", "postit"],
    ),
    spec(
        "board.tool.direct_select",
        "Board",
        "Direct select (anchors)",
        "A — click a path to edit anchors: drag anchors/segments/handles \
         (Alt breaks handle symmetry), double-click toggles corner/smooth, \
         arrows nudge (Shift ×10)",
        Some(Chord::bare(Key::A)),
        Repeat::Repeatable,
        BOARD,
        &["anchors", "direct selection", "path edit"],
    ),
    spec(
        "board.colors.default",
        "Board",
        "Default colors",
        "D — reset foreground/background to the theme ink/paper",
        Some(Chord::bare(Key::D)),
        Repeat::Repeatable,
        BOARD,
        &["reset colors"],
    ),
    spec(
        "board.colors.swap",
        "Board",
        "Swap colors",
        "X — swap foreground ⇄ background",
        Some(Chord::bare(Key::X)),
        Repeat::Repeatable,
        BOARD,
        &["exchange colors"],
    ),
    spec(
        "board.brush.width_down",
        "Board",
        "Brush / eraser width −",
        "[ — steps by the Photoshop screen-px tiers (<10:1 · 10–50:5 · \
         50–100:10 · >100:25); adjusts the eraser while E is armed",
        Some(Chord::bare(Key::OpenBracket)),
        Repeat::Repeatable,
        BOARD,
        &["thinner"],
    ),
    spec(
        "board.brush.width_up",
        "Board",
        "Brush / eraser width +",
        "] — same tiers as [",
        Some(Chord::bare(Key::CloseBracket)),
        Repeat::Repeatable,
        BOARD,
        &["thicker"],
    ),
    spec(
        "board.brush.softness_up",
        "Board",
        "Brush softness +",
        "Shift+[ — softer edge, in 25% steps, while Brush or Eraser is armed",
        Some(shift(Key::OpenBracket)),
        Repeat::Repeatable,
        BOARD,
        &["hardness", "feather"],
    ),
    spec(
        "board.brush.softness_down",
        "Board",
        "Brush softness −",
        "Shift+] — harder edge, in 25% steps, while Brush or Eraser is armed",
        Some(shift(Key::CloseBracket)),
        Repeat::Repeatable,
        BOARD,
        &["hardness", "feather"],
    ),
    spec(
        "board.brush.size_hud",
        "Board",
        "Scrub brush size",
        "Alt+right-drag while Brush or Eraser is armed. The circle stays on \
         the press point and grows about that center. Horizontal changes \
         diameter by one screen pixel per pixel of travel. Vertical changes \
         Brush softness (up softer). Esc restores the values from the press.",
        None,
        Repeat::Never,
        BOARD,
        &["hud", "diameter"],
    ),
    spec(
        "board.brush.color_wheel",
        "Board",
        "Brush color wheel",
        "Ctrl+right-drag while Brush is armed. The wheel opens with the \
         pointer on the current color. 24 recent colors fill equal slots \
         clockwise from 6 o'clock; a repeat moves to 6 o'clock. Choosing a \
         dot keeps the wheel still and moves the pointer onto that color.",
        None,
        Repeat::Never,
        BOARD,
        &["hud", "color", "recent"],
    ),
    spec(
        "board.brush.opacity_hud",
        "Board",
        "Scrub brush opacity",
        "Shift+right-drag while Brush or Eraser is armed (Eraser: strength), with neither Ctrl nor Alt. \
         The circle stays on the press point. Dragging up raises opacity and \
         dragging down lowers it, across 100 screen pixels. The chord does \
         not pan or open the context menu. Esc restores the press.",
        None,
        Repeat::Never,
        BOARD,
        &["hud", "opacity"],
    ),
    spec(
        "board.tool.trim",
        "Board",
        "Trim",
        "Ctrl + T — pick cutting objects, Enter, then click the part to \
         delete. Each click is one undo. Shift+click near a curve end \
         extends it to the cutter. Line cutters extend infinitely.",
        Some(Chord::ctrl(Key::T)),
        Repeat::Repeatable,
        BOARD,
        &["trim", "cut", "split away"],
    ),
    spec(
        "board.tool.split",
        "Board",
        "Split",
        "Ctrl + Shift + T — pick cutting objects, Enter, then click an \
         object to divide. Every piece stays. Each click is one undo. \
         Line cutters extend infinitely.",
        Some(ctrl_shift(Key::T)),
        Repeat::Repeatable,
        BOARD,
        &["split", "divide", "break"],
    ),
    spec(
        "board.path.join",
        "Board",
        "Join paths",
        "Ctrl + J — open paths join at nearest endpoints; closed shapes \
         boolean-union; an open curve in that set is treated as a ribbon \
         of its stroke weight. First selected style wins.",
        Some(Chord::ctrl(Key::J)),
        Repeat::Repeatable,
        BOARD_SEL,
        &["join", "close path", "merge paths", "union"],
    ),
    // ----- board: scene flags (wave 2b) --------------------------------------
    spec(
        "board.group",
        "Board",
        "Group selection",
        "Ctrl + G (2+ objects) — click any member selects the whole group; \
         Ctrl+Shift+click selects a single member",
        Some(Chord::ctrl(Key::G)),
        Repeat::Repeatable,
        BOARD_SEL,
        &["group"],
    ),
    spec(
        "board.ungroup",
        "Board",
        "Ungroup selection",
        "Ctrl + Shift + G",
        Some(ctrl_shift(Key::G)),
        Repeat::Repeatable,
        BOARD_SEL,
        &["ungroup"],
    ),
    spec(
        "board.hide",
        "Board",
        "Hide selection",
        "Ctrl + H — hidden objects leave paint, hit-testing, cycling, \
         present mode, and the export",
        Some(Chord::ctrl(Key::H)),
        Repeat::Repeatable,
        BOARD_SEL,
        &["hide"],
    ),
    spec(
        "board.show_all",
        "Board",
        "Show all hidden",
        "Ctrl + Shift + H (also in the right-click menu on empty canvas)",
        Some(ctrl_shift(Key::H)),
        Repeat::Repeatable,
        BOARD,
        &["show hidden", "unhide"],
    ),
    spec(
        "board.lock",
        "Board",
        "Lock selection",
        "Ctrl + L — locked objects paint normally and stay snap targets, \
         but leave selection and edits; Ctrl+Shift+click force-selects one",
        Some(Chord::ctrl(Key::L)),
        Repeat::Repeatable,
        BOARD_SEL,
        &["lock"],
    ),
    spec(
        "board.unlock_all",
        "Board",
        "Unlock all",
        "Ctrl + Shift + L (also in the right-click menu on empty canvas)",
        Some(ctrl_shift(Key::L)),
        Repeat::Repeatable,
        BOARD,
        &["unlock"],
    ),
    spec(
        "board.subselect",
        "Board",
        "Sub-object select",
        "Ctrl + Shift + click — a single member inside a group, or a locked \
         object (grayed handles, one-off edit)",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    // ----- board: connector wires (wave 2b) ----------------------------------
    spec(
        "board.wire.add",
        "Board",
        "Draw connector (wire)",
        "Hover a node edge (Select tool) → drag from a side grip; snaps to \
         grips/edges within 14 px; release on empty canvas keeps the wire \
         with a free end there; Shift also adds; Esc cancels",
        None,
        Repeat::Never,
        BOARD,
        &["wire", "connector", "connect", "arrow"],
    ),
    spec(
        "board.wire.detach",
        "Board",
        "Detach / rewire a wire",
        "Ctrl + drag from a grip with wires (or drag a selected connector's \
         endpoint dot) — release on a grip/edge rewires, on empty canvas \
         frees the end",
        None,
        Repeat::Never,
        BOARD,
        &["rewire", "disconnect"],
    ),
    spec(
        "board.wire.move_all",
        "Board",
        "Move all wires on a grip",
        "Ctrl + Shift + drag from a grip — every wire end follows; release \
         on a target grip re-anchors all (release on empty cancels)",
        None,
        Repeat::Never,
        BOARD,
        &[],
    ),
    spec(
        "board.wire.label",
        "Board",
        "Connector label / options",
        "Double-click a connector to edit its label; right-click for \
         arrowheads, faint display, and delete",
        None,
        Repeat::Never,
        BOARD,
        &["label", "arrowhead", "faint"],
    ),
    // ----- Presentation ---------------------------------------------------------
    spec(
        "app.present",
        "Presentation",
        "Present frames as slides",
        "F5, or View → Present",
        Some(Chord::bare(Key::F5)),
        Repeat::Repeatable,
        GLOBAL,
        &["slideshow"],
    ),
    spec(
        "present.navigate",
        "Presentation",
        "Navigate slides",
        "← → / Space / PageUp / PageDown / Home / End; click sides",
        None,
        Repeat::Never,
        GLOBAL,
        &[],
    ),
    spec(
        "present.exit",
        "Presentation",
        "Exit presentation",
        "Escape",
        None,
        Repeat::Never,
        GLOBAL,
        &[],
    ),
    spec(
        "app.export",
        "Presentation",
        "Export HTML artifact",
        "Ctrl + E, or File → Export HTML artifact…",
        Some(Chord::ctrl(Key::E)),
        Repeat::Never, // opens a modal folder picker, like open/save
        GLOBAL,
        &[],
    ),
    // ----- Commands (registry meta) -------------------------------------------------
    spec(
        "app.repeat_last",
        "Commands",
        "Repeat last command",
        "Space (tap) or Enter (idle)",
        None, // Space/Enter are handled specially in dispatch.rs
        Repeat::Never,
        GLOBAL,
        &["again"],
    ),
    spec(
        "app.help",
        "Commands",
        "Commands & shortcuts",
        "F1 — opens the Advanced window on the command reference",
        Some(Chord::bare(Key::F1)),
        Repeat::Never,
        GLOBAL,
        &["help", "shortcuts", "keymap"],
    ),
    spec(
        "app.history",
        "Commands",
        "Command history window",
        "F2",
        Some(Chord::bare(Key::F2)),
        Repeat::Never,
        GLOBAL,
        &["log"],
    ),
    spec("board.hover_highlight", "Board", "Hover highlight preferences",
        "Preferences > Advanced settings > Board hover highlights (per primary node type)",
        None, Repeat::Never, GLOBAL, &["hover", "highlight"]),
    spec("app.optional.bumper_cars", "Board", "Bumper cars (optional tool)",
        "Preferences > Configure > Tools > Bumper cars. Off by default; while off, nothing collides and the Bumper squircle is hidden",
        None, Repeat::Never, GLOBAL, &["bumper", "collide", "collision", "puck"]),
    spec("board.bumper.push", "Board", "Bumper cars: push while dragging",
        "Drag a node whose Bumper squircle is On: it pushes other bumper nodes and they glide by their friction after release. Alt passes through; Esc mid-drag puts everything back; one Ctrl+Z undoes the whole shove",
        None, Repeat::Never, BOARD, &["bumper", "collide", "air hockey", "puck"]),
    spec(
        "app.preferences",
        "Commands",
        "Advanced settings",
        "Ctrl + Shift + P, or Preferences → Advanced settings…",
        Some(ctrl_shift(Key::P)),
        Repeat::Never,
        GLOBAL,
        &["settings", "options"],
    ),
    spec(
        "app.properties",
        "Commands",
        "Selection properties",
        "Selection properties live on the object strip above the selection",
        None,
        Repeat::Repeatable,
        GLOBAL,
        &["inspector", "properties"],
    ),
    spec(
        "app.session.mark",
        "Commands",
        "Mark this moment in the session log",
        "F4",
        Some(Chord::bare(Key::F4)),
        Repeat::Never,
        GLOBAL,
        &["mark", "stall", "hitch"],
    ),
    spec(
        "app.session.reveal",
        "Commands",
        "Open session log folder",
        "Advanced → Session log → Open log folder",
        None,
        Repeat::Never,
        GLOBAL,
        &["session log"],
    ),
];

/// Secondary chords: (chord, target command). Checked after the primary
/// registry lookup so one command can own several keys without duplicate ids.
pub static ALIAS_CHORDS: &[(Chord, CommandId)] = &[
    (ctrl_shift(Key::Z), CommandId("app.redo")),
    (Chord::ctrl(Key::B), CommandId("board.to_back")),
    (Chord::bare(Key::F7), CommandId("board.grid")),
    (Chord::bare(Key::Backspace), CommandId("board.delete")),
];

/// The app's registry view over [`SPECS`].
pub fn registry() -> Registry {
    Registry::new(SPECS)
}

/// Reference table for Advanced settings, rendered from [`SPECS`] so the
/// window and the dispatcher can never disagree.
pub fn shortcuts_reference_ui(ui: &mut Ui) {
    let entries: Vec<CommandEntry> = SPECS
        .iter()
        .map(|s| CommandEntry {
            category: s.category,
            name: s.name,
            binding: s.binding,
        })
        .collect();
    atlas_shell::commands::shortcuts_reference_ui(ui, &entries, "apps/slate/src/app/commands.rs");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn registry_validates() {
        registry().validate().expect("SPECS table is consistent");
    }

    #[test]
    fn alias_chords_resolve_and_do_not_collide() {
        let reg = registry();
        for (chord, id) in ALIAS_CHORDS {
            let spec = reg.by_id(*id).expect("alias target exists");
            // An alias must not shadow a primary chord that is live in any of
            // the target's views.
            if let Some(other) = reg.by_chord(*chord, spec.when.union(Availability::GLOBAL)) {
                panic!(
                    "alias {:?} for `{}` collides with primary chord of `{}`",
                    chord, id.0, other.id.0
                );
            }
        }
    }

    #[test]
    fn never_repeat_set_matches_spec() {
        // The command-registry spec's never-repeat set: undo/redo/save/save-as/
        // open/new-tab/escape/delete/zoom/fit/select-all/history/help/repeat.
        let reg = registry();
        for id in [
            "app.undo",
            "app.redo",
            "app.save",
            "app.save_as",
            "app.open",
            "app.new_tab",
            "app.cancel",
            "board.delete",
            "canvas.zoom_in",
            "board.fit",
            "app.select_all",
            "app.history",
            "app.help",
            "app.repeat_last",
            "app.session.mark",
            "app.session.reveal",
        ] {
            let spec = reg.by_id(CommandId(id)).expect(id);
            assert_eq!(spec.repeat, Repeat::Never, "{id} must be never-repeat");
        }
    }
}
