"""Build review-only vector specimens; does not change application icons."""
from pathlib import Path
import json

ROOT = Path(__file__).parent
# Approved geometry is owned by atlas-shell; this is a separate preview interpreter.
CATALOG = json.loads((ROOT.parents[1] / 'crates/atlas-shell/assets/tool-icons.json').read_text(encoding='utf-8'))
DATA = [{'name': 'Select', 'id': 'Select', 'solid': True}, {'name': 'Direct select', 'id': 'DirectSelect', 'solid': False}, {'name': 'Pan', 'id': 'Pan', 'solid': True}, {'name': 'Frame', 'id': 'Frame', 'solid': False}, {'name': 'Rectangle', 'id': 'Rect', 'solid': False}, {'name': 'Ellipse', 'id': 'Ellipse', 'solid': False}, {'name': 'Line', 'id': 'Line', 'solid': False}, {'name': 'Arc', 'id': 'Arc', 'solid': False}, {'name': 'Polyline', 'id': 'Polyline', 'solid': False}, {'name': 'Bezier', 'id': 'Bezier', 'solid': False}, {'name': 'Pen', 'id': 'Pen', 'solid': True}, {'name': 'Text', 'id': 'Text', 'solid': False}, {'name': 'Measure', 'id': 'Ruler', 'solid': False}, {'name': 'Trim', 'id': 'Trim', 'solid': False}, {'name': 'Join', 'id': 'Join', 'solid': False}, {'name': 'Split', 'id': 'Split', 'solid': False}, {'name': 'Portals', 'id': 'Portals', 'solid': True}, {'name': 'Web', 'id': 'WebPortal', 'solid': False}, {'name': 'Tags', 'id': 'Tags', 'solid': True}, {'name': 'Filters', 'id': 'Filters', 'solid': False}, {'name': 'Grid', 'id': 'Grid', 'solid': False}, {'name': 'Snap', 'id': 'Snap', 'solid': True}, {'name': 'Folder map', 'id': 'AtlasLens', 'solid': False}, {'name': 'Fit view', 'id': 'Fit', 'solid': False}]
PRIMARY = [{'name': 'Frame', 'app': 'Slate', 'id': 'Frame', 'why': 'A page silhouette with one dog-ear, at the proposed size aspect, identifies a frame without using Figma-style rails or a generic square.'}, {'name': 'Portals', 'app': 'Slate', 'id': 'Portals', 'why': 'An opening inside a boundary: a view into another source. One broad symbol for all portal types.'}, {'name': 'Shapes', 'app': 'Slate', 'id': 'Shapes', 'why': 'A square and circle communicate the family; individual shapes remain in the flyout.'}, {'name': 'Text', 'app': 'Slate', 'id': 'Text', 'why': 'A familiar typographic T covers text and notes without adding a second miniature icon.'}, {'name': 'Actions', 'app': 'Slate', 'id': 'Actions', 'why': 'An editing wrench represents the command family. Trim no longer stands in for Split and Join. Review whether this reads too much like settings.'}, {'name': 'Object properties', 'app': 'Slate', 'id': 'ObjectProperties', 'why': 'An object divided into property regions covers appearance and tags. More general than the existing color swatches.'}, {'name': 'Document settings', 'app': 'Slate', 'id': 'DocumentSettings', 'why': 'A page with two adjustment tracks gives document-wide settings an identity beyond the grid toggle.'}, {'name': 'Selection', 'app': 'Slate', 'id': 'Selection', 'why': 'A bounded object identifies the selection inspector. It stays distinct from the Select cursor and Fit view.'}, {'name': 'Basic filters', 'app': 'File Atlas', 'id': 'Filters', 'why': 'A funnel says filter immediately, keeping adjustment sliders available for settings.'}, {'name': 'Display settings', 'app': 'File Atlas', 'id': 'Display', 'why': 'A display with arranged content covers tree, packing, density, and previews without choosing one layout.'}, {'name': 'Mode', 'app': 'File Atlas', 'id': 'Mode', 'why': 'A lock foregrounds safe View mode. Any live View/Edit lock variant must mirror existing state and keep the explicit label; this specimen is View.'}, {'name': 'Workflow', 'app': 'File Atlas', 'id': 'Workflow', 'why': 'Connected stages express assignment and export preparation, rather than a generic checklist.'}, {'name': 'AI · Cursor', 'app': 'File Atlas', 'id': 'Ai', 'why': 'A prompt inside a conversation bubble represents the agent workspace. It keeps identity independent of a provider logo.'}]
DATA.extend([
    {'name': 'Image', 'id': 'Image', 'solid': False},
    {'name': '3D', 'id': 'Model', 'solid': False},
    {'name': 'Video', 'id': 'Video', 'solid': False},
    {'name': 'Letter', 'id': 'FrameLetter', 'solid': False},
    {'name': 'Tabloid', 'id': 'FrameTabloid', 'solid': False},
    {'name': '16:9', 'id': 'FrameWide', 'solid': False},
    {'name': 'Custom frame', 'id': 'FrameCustom', 'solid': False},
])
PRIMARY.insert(0, {'name': 'Media', 'app': 'Slate', 'id': 'Media', 'why': 'Stacked sheets identify linked media as a family. Image, Rhino 3D, and Video retain separate child glyphs.'})
for item in DATA + PRIMARY:
    item['path'] = CATALOG[item['id']]['path']
    item.setdefault('solid', False)
RULES = [
 'Draw on a 24 × 24 master; target a 20 × 20 optical footprint with 2-unit padding.',
 'A uses a 1.5-unit stroke; B uses 1.75 units and selected solid silhouettes. Choose one family for the product.',
 'Use rounded caps and joins consistently. Preserve sharp corners where they carry meaning, such as the selection arrow.',
 'Use one neutral ink color. Blue signals the active tool; a visible background shape also communicates selection.',
 'Keep at least 2 units between internal features. At 16 px, remove secondary detail before making strokes thinner.',
 'One primary metaphor per icon. Distinguish siblings by geometry: frame vs rectangle, pen vs Bezier, trim vs split.',
 'Reserve solid Select and hollow Direct select as a semantic pair. Do not fill every closed shape.',
 'Glyph size and hit area are separate. Review 16/20/24 px glyphs inside the existing shared dock targets; propose 32 px minimum targets separately.',
 'Idle, hover, active, disabled, focus, and pinned are separate states. Keep glyph geometry fixed between them; preserve existing dock semantics.',
 'Maintain tooltips and command names. Never depend on color or an unfamiliar pictogram alone to explain a new tool.',
 'One shared owner for geometry and styling in atlas-shell. Apps map commands to icon IDs; custom painters must use the same metrics.',
 'Before shipping, inspect both themes at 100/125/150/200% Windows scaling. Review dense siblings at actual size, not only enlarged.',
]

HTML = '''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Atlas / Slate · Tool icon proposals</title>
<style>
:root{--bg:#f6f7f9;--panel:#fff;--ink:#24272e;--muted:#676d77;--line:#dce0e6;--accent:#1459df;--hover:#e9edf4;--on:#fff}body.dark{--bg:#17191d;--panel:#23262c;--ink:#f1f3f7;--muted:#a2a9b5;--line:#3b414b;--hover:#343a45;--accent:#3978f5}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:14px/1.6 'Segoe UI',sans-serif}main{max-width:1240px;margin:auto;padding:36px}h1{font-size:28px;font-weight:600;margin:4px 0 8px}h2{font-size:21px;font-weight:600}h3{font-size:16px}p{color:var(--muted);max-width:780px}small,.eyebrow{color:var(--muted)}.eyebrow{font-size:11px;letter-spacing:2px;text-transform:uppercase}.controls{display:flex;gap:18px;align-items:center;flex-wrap:wrap;border-block:1px solid var(--line);padding:16px 0;margin:24px 0}button,select{background:var(--panel);color:var(--ink);border:1px solid var(--line);border-radius:6px;padding:8px 12px;font:inherit;cursor:pointer}button:hover{background:var(--hover)}button:focus-visible{outline:2px solid var(--accent);outline-offset:3px}.directions{display:grid;grid-template-columns:1fr 1fr;gap:28px}.family{min-width:0}.sample{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:16px}.toolbar{display:flex;gap:4px;flex-wrap:wrap;padding:8px 0 20px;border-bottom:1px solid var(--line);margin-bottom:16px}.tool{border:0;width:36px;height:36px;padding:0;display:inline-flex;align-items:center;justify-content:center;border-radius:6px;background:transparent}.tool.active{background:var(--accent);color:var(--on)}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:20px 8px}.cell{text-align:center;font-size:11px;color:var(--muted)}.cell svg{display:block;margin:0 auto 9px;color:var(--ink)}svg{flex-shrink:0}.statebar{display:flex;gap:20px;margin-top:24px;flex-wrap:wrap}.state{text-align:center;font-size:11px;color:var(--muted)}.state button{display:flex;margin-bottom:6px}.rules{columns:2;column-gap:48px;padding-left:20px}.rules li{break-inside:avoid;margin-bottom:14px;padding-left:4px}a{color:var(--accent)}section{margin-top:36px}.recommend{border-left:3px solid var(--accent);padding-left:16px}.note{font-size:12px}.chosen{font-size:12px;color:var(--accent)}@media(max-width:800px){main{padding:20px}.directions{grid-template-columns:1fr}.rules{columns:1}}
</style><main><div class="eyebrow">Atlas / Slate · Design proposal · 15 September 2026</div><h1>A calmer, more legible tool palette</h1><p>Two original vector directions inspired by Figma’s restraint. The same 24 tools are drawn in both families so you can judge recognition and density fairly. Quiet outline is applied in the project; Bold silhouette remains a comparison.</p>
<div class="controls"><button id="theme">Switch to dark</button><label>Glyph size <select id="size"><option>16</option><option selected>20</option><option>24</option><option>32</option></select> px</label><label><input type="checkbox" id="labels" checked> Show names</label><span class="chosen" id="selection">Click a toolbar tool to inspect its active state.</span></div>
<div class="directions" id="directions"></div>
<section class="recommend"><h2>Recommendation: A / Quiet outline</h2><p>Use A as the base: lighter visual weight, clear negative space, and less competition with the board. Keep its solid selection arrow. B offers stronger silhouettes for quick scanning, but filled object tools can become visually dominant.</p></section>
<section><h2>What changes first</h2><p><b>Select / Pan:</b> recognizable arrow and continuous hand contour. <b>Frame / Rectangle:</b> extended frame rails versus a closed shape. <b>Arc / Polyline / Bezier:</b> smooth curvature versus angular vertices versus explicit control handles. <b>Trim / Split / Join:</b> removed side, separated pieces, joined endpoints. These metaphors need a short recognition review before adoption.</p></section>
<section><h2>Proposed rules for future icons</h2><ol class="rules" id="rules"></ol></section>
<section><h2>Review before implementation</h2><p>Compare at 20 px first, then 16 px. Toggle dark mode. Check whether neighboring tools remain distinguishable without labels. The state examples illustrate visual treatment only; changing click, hover, pin, or flyout behavior requires a separate interaction decision.</p><p class="note">Figma inspiration: <a href="https://www.figma.com/blog/behind-our-redesign-ui3/">UI3 design rationale</a> and <a href="https://help.figma.com/hc/en-us/articles/360041064174-Access-design-tools-from-the-toolbar">toolbar reference</a>. Measurements here are our proposal, not Figma specifications. Current code reviewed: apps/slate/src/app/board_icons.rs and crates/atlas-shell/src/dock.rs.</p></section></main>
<script>const icons=__DATA__;const rules=__RULES__;let size=20,selected='Select';
function glyph(i,b){let fill=(i.name==='Select'||(b&&i.solid))?'currentColor':'none';return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" aria-hidden="true" fill="${fill}" fill-rule="evenodd" stroke="currentColor" stroke-width="${b?1.75:1.5}" stroke-linecap="round" stroke-linejoin="round"><path d="${i.path}"/></svg>`}
function draw(){document.querySelector('#directions').innerHTML=[false,true].map(b=>`<article class="family"><h2>${b?'B / Bold silhouette':'A / Quiet outline'}</h2><p>${b?'Stronger shapes, selective fill, confident at small sizes.':'Fine, even strokes. Airy and deliberately understated.'}</p><div class="sample"><div class="toolbar">${icons.slice(0,8).map(i=>`<button class="tool ${selected===i.name?'active':''}" title="${i.name}" aria-label="${i.name}" aria-pressed="${selected===i.name}" data-name="${i.name}">${glyph(i,b)}</button>`).join('')}</div><div class="grid">${icons.map(i=>`<div class="cell">${glyph(i,b)}<span ${document.querySelector('#labels').checked?'':'hidden'}>${i.name}</span></div>`).join('')}</div><div class="statebar">${['Idle','Hover','Active','Disabled','Focus'].map((s,k)=>`<div class="state"><button class="tool ${k===2?'active':''}" ${k===3?'disabled':''} style="${k===1?'background:var(--hover)':k===3?'opacity:.35':k===4?'outline:2px solid var(--accent);outline-offset:2px':''}" aria-label="${s} frame example">${glyph(icons[3],b)}</button>${s}</div>`).join('')}</div></div></article>`).join('');document.querySelectorAll('[data-name]').forEach(el=>el.onclick=()=>{selected=el.dataset.name;draw();document.querySelector('#selection').textContent='Active preview: '+selected})}
document.querySelector('#rules').innerHTML=rules.map(r=>`<li>${r}</li>`).join('');document.querySelector('#theme').onclick=()=>{document.body.classList.toggle('dark');document.querySelector('#theme').textContent=document.body.classList.contains('dark')?'Switch to light':'Switch to dark'};document.querySelector('#size').onchange=e=>{size=+e.target.value;draw()};document.querySelector('#labels').onchange=draw;draw();</script></html>'''
HTML = HTML.replace('<div class="directions" id="directions">', '''<section id="primary"><div class="eyebrow">New · Primary palette icons</div><h2>Clear identities for the main palette</h2><p>The current eight Slate launchers and five File Atlas launchers, redrawn in Quiet outline. Click a primary icon for its reasoning. These strips show glyphs in context; they do not propose a new dock layout.</p><div id="primary-strips"></div><p id="primary-detail" class="recommend" aria-live="polite">Portals — An opening inside a boundary: a view into another source.</p></section><section><h2>Individual tools · A / B comparison</h2></section><div class="directions" id="directions">''')
HTML = HTML.replace('</style>', '.cell .tool svg{color:inherit;margin:0}</style>')
HTML = HTML.replace('const icons=__DATA__;', 'const primaryIcons=__PRIMARY__; let primarySelected="Portals"; const icons=__DATA__;')
HTML = HTML.replace('function draw(){', '''function drawPrimary(){document.querySelector('#primary-strips').innerHTML=['Slate','File Atlas'].map(app=>`<h3>${app}</h3><div class="sample" style="display:flex;gap:12px;flex-wrap:wrap">${primaryIcons.filter(i=>i.app===app).map(i=>`<div class="cell" style="width:76px"><button class="tool ${primarySelected===i.name?'active':''}" style="width:44px;height:44px" title="${i.name}" aria-label="Primary ${i.name}" aria-pressed="${primarySelected===i.name}" data-primary="${i.name}">${glyph(i,false)}</button><div ${document.querySelector('#labels').checked?'':'hidden'}>${i.name}</div></div>`).join('')}</div>`).join('');document.querySelectorAll('[data-primary]').forEach(el=>el.onclick=()=>{primarySelected=el.dataset.primary;document.querySelector('#primary-detail').textContent=primarySelected+' — '+primaryIcons.find(i=>i.name===primarySelected).why;drawPrimary()})}
function draw(){drawPrimary();''')
(ROOT/'proposal.html').write_text(HTML.replace('__PRIMARY__',json.dumps(PRIMARY)).replace('__DATA__',json.dumps(DATA)).replace('__RULES__',json.dumps(RULES)),encoding='utf-8')

CANVAS = '''import { useState, useHostTheme, H1, H2, Text } from "cursor/canvas";
const icons = __DATA__;
const rules = __RULES__;
export default function ToolIconDirections(){
 const t=useHostTheme(); const [size,setSize]=useState(20); const [selected,setSelected]=useState('Select');
 const glyph=(i:typeof icons[number],bold:boolean)=><svg width={size} height={size} viewBox="0 0 24 24" aria-hidden="true" fill={i.name==='Select'||(bold&&i.solid)?'currentColor':'none'} fillRule="evenodd" stroke="currentColor" strokeWidth={bold?1.75:1.5} strokeLinecap="round" strokeLinejoin="round"><path d={i.path}/></svg>;
 return <main style={{padding:24,color:t.text.primary,background:t.bg.editor,fontFamily:'sans-serif'}}><H1>Tool palette: two icon directions</H1><Text>Original vector proposals inspired by Figma’s restraint. Quiet outline is applied in the project.</Text><div style={{display:'flex',gap:12,alignItems:'center',margin:'20px 0'}}><label>Glyph size <select value={size} onChange={e=>setSize(Number(e.target.value))}>{[16,20,24,32].map(s=><option key={s}>{s}</option>)}</select> px</label><span style={{color:t.text.secondary}}>Click an icon to compare its active state.</span></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:24}}>{[false,true].map(b=><section key={String(b)}><H2>{b?'B / Bold silhouette':'A / Quiet outline · Recommended'}</H2><Text>{b?'Stronger weight and selective solid shapes.':'Fine strokes, open interiors, a clear solid cursor.'}</Text><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:16,padding:16,marginTop:16,background:t.bg.elevated,border:`1px solid ${t.stroke.primary}`,borderRadius:8}}>{icons.map(i=><div key={i.name} style={{textAlign:'center'}}><button aria-label={i.name} aria-pressed={selected===i.name} onClick={()=>setSelected(i.name)} style={{width:40,height:40,display:'inline-flex',alignItems:'center',justifyContent:'center',border:0,borderRadius:6,cursor:'pointer',background:selected===i.name?t.accent.control:'transparent',color:selected===i.name?t.text.onAccent:t.text.primary}}>{glyph(i,b)}</button><div style={{fontSize:11,color:t.text.secondary,marginTop:4}}>{i.name}</div></div>)}</div></section>)}</div><section style={{marginTop:28}}><H2>Why A</H2><Text>Its lighter visual weight leaves attention on the board. Keep Select solid and Direct select hollow. Preserve recognizable silhouettes; simplify detail rather than thinning every line.</Text><H2>Proposed development rules</H2><ol>{rules.map(r=><li key={r} style={{marginBottom:12,lineHeight:1.5}}>{r}</li>)}</ol><Text>Quiet outline approved. Review both themes and Windows scaling when changing icons. The HTML companion adds theme switching and hover, active, disabled, and focus specimens.</Text><a href="https://www.figma.com/blog/behind-our-redesign-ui3/" style={{color:t.text.link}}>Figma UI3 reference</a><Text>All measurements are proposed Atlas / Slate rules, not Figma specifications.</Text></section></main>
}'''
canvas_path=Path.home()/'.cursor/projects/c-Users-jmoser-source-repos-AtlasFileExplorer/canvases/tool-icon-directions.canvas.tsx'
CANVAS = CANVAS.replace('const icons = __DATA__;', 'const primaryIcons = __PRIMARY__;\nconst icons = __DATA__;')
CANVAS = CANVAS.replace("<H1>Tool palette: two icon directions</H1>", '''<H1>Tool palette: primary icons and tool families</H1><H2>New · Primary palette icons</H2>{['Slate','File Atlas'].map(app=><section key={app}><H2>{app}</H2><div style={{display:'flex',gap:12,flexWrap:'wrap',marginBottom:16}}>{primaryIcons.filter(i=>i.app===app).map(i=><button key={i.name} title={i.why} onClick={()=>setSelected(i.name)} style={{width:90,padding:8,border:`1px solid ${t.stroke.primary}`,borderRadius:6,background:selected===i.name?t.accent.control:t.bg.elevated,color:selected===i.name?t.text.onAccent:t.text.primary,cursor:'pointer'}}>{glyph(i,false)}<div style={{fontSize:11,marginTop:8}}>{i.name}</div></button>)}</div></section>)}<Text>{primaryIcons.find(i=>i.name===selected)?.why || 'Select a primary icon to read its design reasoning.'}</Text><H2>Individual tools</H2>''')
canvas_path.write_text(CANVAS.replace('__PRIMARY__',json.dumps(PRIMARY)).replace('__DATA__',json.dumps(DATA)).replace('__RULES__',json.dumps(RULES)),encoding='utf-8')
print(ROOT/'proposal.html')
print(canvas_path)
