//! Shared fixtures for the Slate app tests.

use super::*;

mod agent_send;
mod align_sweep;
mod arming_paint;
mod atlas_lens;
mod bezier_math;
mod bezier_place;
mod big_brush;
mod brush_anchor;
mod brush_live;
mod brush_marks;
mod brush_stamp;
mod chords;
mod clipboard_bitmap;
mod closed_forms;
mod crop_board;
mod curve_handles;
mod deck;
mod dock_strip;
mod draft_pointer;
mod eraser_band;
mod eraser_bar;
mod eraser_flick;
mod eraser_watch;
mod escape_board;
mod fixtures_pdf;
mod frame_raster;
mod grips;
mod harness;
mod image_layers;
mod join_geom;
mod kit_drag;
mod line_board;
mod nested_bar;
mod office_stubs;
mod osnap;
mod page_wheel;
mod pen_strokes;
mod pictures;
mod pointer;
mod pump;
mod shapes;
mod slice_arm;
mod text_draft;
mod tip_hud_input;
mod vertex_ink;
mod web_host;

pub(crate) use agent_send::*;
pub(crate) use align_sweep::*;
pub(crate) use arming_paint::*;
pub(crate) use atlas_lens::*;
pub(crate) use bezier_math::*;
pub(crate) use bezier_place::*;
pub(crate) use big_brush::*;
pub(crate) use brush_anchor::*;
pub(crate) use brush_live::*;
pub(crate) use brush_marks::*;
pub(crate) use brush_stamp::*;
pub(crate) use chords::*;
pub(crate) use clipboard_bitmap::*;
pub(crate) use closed_forms::*;
pub(crate) use crop_board::*;
pub(crate) use curve_handles::*;
pub(crate) use deck::*;
pub(crate) use dock_strip::*;
pub(crate) use draft_pointer::*;
pub(crate) use eraser_band::*;
pub(crate) use eraser_bar::*;
pub(crate) use eraser_flick::*;
pub(crate) use eraser_watch::*;
pub(crate) use escape_board::*;
pub(crate) use fixtures_pdf::*;
pub(crate) use frame_raster::*;
pub(crate) use grips::*;
pub(crate) use harness::*;
pub(crate) use image_layers::*;
pub(crate) use join_geom::*;
pub(crate) use kit_drag::*;
pub(crate) use line_board::*;
pub(crate) use nested_bar::*;
pub(crate) use office_stubs::*;
pub(crate) use osnap::*;
pub(crate) use page_wheel::*;
pub(crate) use pen_strokes::*;
pub(crate) use pictures::*;
pub(crate) use pointer::*;
pub(crate) use pump::*;
pub(crate) use shapes::*;
pub(crate) use slice_arm::*;
pub(crate) use text_draft::*;
pub(crate) use tip_hud_input::*;
pub(crate) use vertex_ink::*;
pub(crate) use web_host::*;
